/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author jescalaya
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpFondoMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMantenimientoTablas = new javax.swing.JMenu();
        mnuMovimientos = new javax.swing.JMenu();
        mnuMovimientosRegistroRecepcion = new javax.swing.JMenuItem();
        mnuMovimientoRegistroReimprimirPaleta = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        mnuReporteCuadroResumen = new javax.swing.JMenuItem();
        mnuReportePaletaProceso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Recepción de Materia Prima");
        setName("frmPrincipal"); // NOI18N

        javax.swing.GroupLayout dkpFondoMenuLayout = new javax.swing.GroupLayout(dkpFondoMenu);
        dkpFondoMenu.setLayout(dkpFondoMenuLayout);
        dkpFondoMenuLayout.setHorizontalGroup(
            dkpFondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1242, Short.MAX_VALUE)
        );
        dkpFondoMenuLayout.setVerticalGroup(
            dkpFondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        mnuMantenimientoTablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/mantenimientoTablas.png"))); // NOI18N
        mnuMantenimientoTablas.setText("Mantenimiento Tablas");
        jMenuBar1.add(mnuMantenimientoTablas);

        mnuMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/movimientos.png"))); // NOI18N
        mnuMovimientos.setText("Movimientos");

        mnuMovimientosRegistroRecepcion.setText("Registro Recepción de Materia Prima");
        mnuMovimientosRegistroRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimientosRegistroRecepcionActionPerformed(evt);
            }
        });
        mnuMovimientos.add(mnuMovimientosRegistroRecepcion);

        mnuMovimientoRegistroReimprimirPaleta.setText("Reimprimir Paleta");
        mnuMovimientos.add(mnuMovimientoRegistroReimprimirPaleta);

        jMenuBar1.add(mnuMovimientos);

        mnuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/reporte.png"))); // NOI18N
        mnuReporte.setText("Reportes");

        mnuReporteCuadroResumen.setText("Cuadro Resumen");
        mnuReporte.add(mnuReporteCuadroResumen);

        mnuReportePaletaProceso.setText("Paletas en Proceso");
        mnuReporte.add(mnuReportePaletaProceso);

        jMenuBar1.add(mnuReporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpFondoMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpFondoMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMovimientosRegistroRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimientosRegistroRecepcionActionPerformed
        frmRegistroRecepcionFruta recepcion = new frmRegistroRecepcionFruta();
        this.dkpFondoMenu.add(recepcion);
        recepcion.setVisible(true);
    }//GEN-LAST:event_mnuMovimientosRegistroRecepcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dkpFondoMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuMantenimientoTablas;
    private javax.swing.JMenuItem mnuMovimientoRegistroReimprimirPaleta;
    private javax.swing.JMenu mnuMovimientos;
    private javax.swing.JMenuItem mnuMovimientosRegistroRecepcion;
    private javax.swing.JMenu mnuReporte;
    private javax.swing.JMenuItem mnuReporteCuadroResumen;
    private javax.swing.JMenuItem mnuReportePaletaProceso;
    // End of variables declaration//GEN-END:variables
}
